/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminSettings {
  'instagramApiKey' : string,
  'comingSoonEnabled' : boolean,
  'tiktokApiKey' : string,
}
export interface BlogCategory {
  'id' : string,
  'name' : string,
  'description' : string,
  'timestamp' : Time,
}
export interface BlogPost {
  'id' : string,
  'categories' : Array<string>,
  'title' : string,
  'content' : string,
  'published' : boolean,
  'tags' : Array<string>,
  'publishedAt' : [] | [Time],
  'directPublish' : boolean,
  'author' : string,
  'coverImage' : [] | [string],
  'timestamp' : Time,
  'excerpt' : string,
  'scheduledAt' : [] | [Time],
  'images' : Array<string>,
}
export interface ContactSubmission {
  'id' : string,
  'consent' : boolean,
  'subject' : string,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface EmailCapture { 'email' : string, 'timestamp' : Time }
export interface FileReference { 'hash' : string, 'path' : string }
export interface InstagramFeedItem {
  'id' : string,
  'link' : [] | [string],
  'published' : boolean,
  'mediaUrl' : string,
  'story' : boolean,
  'timestamp' : Time,
  'caption' : string,
  'mediaType' : string,
}
export interface ShopCategory {
  'id' : string,
  'name' : string,
  'description' : string,
  'timestamp' : Time,
}
export interface ShopProduct {
  'id' : string,
  'title' : string,
  'featured' : boolean,
  'inventory' : bigint,
  'published' : boolean,
  'popular' : boolean,
  'description' : string,
  'timestamp' : Time,
  'category' : string,
  'affiliateLink' : string,
  'price' : number,
  'images' : Array<string>,
}
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'language' : string,
  'newsletter' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<string>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<string>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addBlogCategory' : ActorMethod<[BlogCategory], undefined>,
  'addInstagramFeedItem' : ActorMethod<[InstagramFeedItem], undefined>,
  'addShopCategory' : ActorMethod<[ShopCategory], undefined>,
  'addShopProduct' : ActorMethod<[ShopProduct], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'captureEmail' : ActorMethod<[EmailCapture], undefined>,
  'createBlogPost' : ActorMethod<[BlogPost], undefined>,
  'deleteBlogCategory' : ActorMethod<[string], undefined>,
  'deleteBlogPost' : ActorMethod<[string], undefined>,
  'deleteInstagramFeedItem' : ActorMethod<[string], undefined>,
  'deleteShopCategory' : ActorMethod<[string], undefined>,
  'deleteShopProduct' : ActorMethod<[string], undefined>,
  'dropFileReference' : ActorMethod<[string], undefined>,
  'fetchInstagramFeed' : ActorMethod<[], string>,
  'fetchInstagramLogo' : ActorMethod<[], string>,
  'fetchTikTokFeed' : ActorMethod<[], string>,
  'getAdminSettings' : ActorMethod<[], [] | [AdminSettings]>,
  'getAllBlogCategories' : ActorMethod<[], Array<BlogCategory>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllBlogViewCounts' : ActorMethod<[], Array<[string, bigint]>>,
  'getAllCapturedEmails' : ActorMethod<[], Array<EmailCapture>>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getAllInstagramFeedItems' : ActorMethod<[], Array<InstagramFeedItem>>,
  'getAllShopCategories' : ActorMethod<[], Array<ShopCategory>>,
  'getAllShopProducts' : ActorMethod<[], Array<ShopProduct>>,
  'getAllUsersWithProfiles' : ActorMethod<
    [],
    Array<[Principal, [] | [UserProfile]]>
  >,
  'getBlogPost' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogPostsByAuthor' : ActorMethod<[string], Array<BlogPost>>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getBlogPostsByTag' : ActorMethod<[string], Array<BlogPost>>,
  'getBlogViewCount' : ActorMethod<[string], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFileReference' : ActorMethod<[string], FileReference>,
  'getInstagramStories' : ActorMethod<[], Array<InstagramFeedItem>>,
  'getLatestBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getPopularShopProducts' : ActorMethod<[], Array<ShopProduct>>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getPublishedBlogsPaginated' : ActorMethod<[bigint, bigint], Array<BlogPost>>,
  'getPublishedInstagramFeedItems' : ActorMethod<[], Array<InstagramFeedItem>>,
  'getPublishedShopProducts' : ActorMethod<[], Array<ShopProduct>>,
  'getShopProductsByCategory' : ActorMethod<[string], Array<ShopProduct>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'incrementBlogViewCount' : ActorMethod<[string], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listFileReferences' : ActorMethod<[], Array<FileReference>>,
  'registerFileReference' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[ContactSubmission], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'triggerPublicationCheck' : ActorMethod<[], undefined>,
  'updateAdminSettings' : ActorMethod<[AdminSettings], undefined>,
  'updateBlogCategory' : ActorMethod<[BlogCategory], undefined>,
  'updateBlogPost' : ActorMethod<[BlogPost], undefined>,
  'updateInstagramFeedItem' : ActorMethod<[InstagramFeedItem], undefined>,
  'updateShopCategory' : ActorMethod<[ShopCategory], undefined>,
  'updateShopProduct' : ActorMethod<[ShopProduct], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];