/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const BlogCategory = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const InstagramFeedItem = IDL.Record({
  'id' : IDL.Text,
  'link' : IDL.Opt(IDL.Text),
  'published' : IDL.Bool,
  'mediaUrl' : IDL.Text,
  'story' : IDL.Bool,
  'timestamp' : Time,
  'caption' : IDL.Text,
  'mediaType' : IDL.Text,
});
export const ShopCategory = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
});
export const ShopProduct = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'inventory' : IDL.Nat,
  'published' : IDL.Bool,
  'popular' : IDL.Bool,
  'description' : IDL.Text,
  'timestamp' : Time,
  'category' : IDL.Text,
  'affiliateLink' : IDL.Text,
  'price' : IDL.Float64,
  'images' : IDL.Vec(IDL.Text),
});
export const TravelStyle = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'timestamp' : Time,
  'baseImage' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EmailCapture = IDL.Record({
  'email' : IDL.Text,
  'timestamp' : Time,
});
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'categories' : IDL.Vec(IDL.Text),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'published' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Opt(Time),
  'directPublish' : IDL.Bool,
  'author' : IDL.Text,
  'coverImage' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'excerpt' : IDL.Text,
  'scheduledAt' : IDL.Opt(Time),
  'images' : IDL.Vec(IDL.Text),
});
export const AdminSettings = IDL.Record({
  'instagramApiKey' : IDL.Text,
  'comingSoonEnabled' : IDL.Bool,
  'tiktokApiKey' : IDL.Text,
});
export const ContactSubmission = IDL.Record({
  'id' : IDL.Text,
  'consent' : IDL.Bool,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'language' : IDL.Text,
  'newsletter' : IDL.Bool,
});
export const BuildFailure = IDL.Record({
  'failed_attempts' : IDL.Nat,
  'failed_step' : IDL.Text,
  'error_message' : IDL.Text,
  'timestamp' : Time,
  'environment' : IDL.Text,
});
export const DeploymentFailure = IDL.Record({
  'failed_attempts' : IDL.Nat,
  'failed_step' : IDL.Text,
  'error_message' : IDL.Text,
  'timestamp' : Time,
  'environment' : IDL.Text,
});
export const FileReference = IDL.Record({
  'hash' : IDL.Text,
  'path' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TravelStyleUpdate = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'baseImage' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addBlogCategory' : IDL.Func([BlogCategory], [], []),
  'addInstagramFeedItem' : IDL.Func([InstagramFeedItem], [], []),
  'addShopCategory' : IDL.Func([ShopCategory], [], []),
  'addShopProduct' : IDL.Func([ShopProduct], [], []),
  'addTravelStyle' : IDL.Func([TravelStyle], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'captureEmail' : IDL.Func([EmailCapture], [], []),
  'createBlogPost' : IDL.Func([BlogPost], [], []),
  'deleteBlogCategory' : IDL.Func([IDL.Text], [], []),
  'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
  'deleteInstagramFeedItem' : IDL.Func([IDL.Text], [], []),
  'deleteShopCategory' : IDL.Func([IDL.Text], [], []),
  'deleteShopProduct' : IDL.Func([IDL.Text], [], []),
  'deleteTravelStyle' : IDL.Func([IDL.Text], [], []),
  'dropFileReference' : IDL.Func([IDL.Text], [], []),
  'fetchInstagramFeed' : IDL.Func([], [IDL.Text], []),
  'fetchInstagramLogo' : IDL.Func([], [IDL.Text], []),
  'fetchTikTokFeed' : IDL.Func([], [IDL.Text], []),
  'getAdminSettings' : IDL.Func([], [IDL.Opt(AdminSettings)], ['query']),
  'getAllBlogCategories' : IDL.Func([], [IDL.Vec(BlogCategory)], ['query']),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllBlogViewCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getAllCapturedEmails' : IDL.Func([], [IDL.Vec(EmailCapture)], ['query']),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getAllInstagramFeedItems' : IDL.Func(
      [],
      [IDL.Vec(InstagramFeedItem)],
      ['query'],
    ),
  'getAllShopCategories' : IDL.Func([], [IDL.Vec(ShopCategory)], ['query']),
  'getAllShopProducts' : IDL.Func([], [IDL.Vec(ShopProduct)], ['query']),
  'getAllTravelStyles' : IDL.Func([], [IDL.Vec(TravelStyle)], ['query']),
  'getAllUsersWithProfiles' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(UserProfile)))],
      ['query'],
    ),
  'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
  'getBlogPostsByAuthor' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
  'getBlogPostsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getBlogPostsByTag' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
  'getBlogViewCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getBuildFailures' : IDL.Func([], [IDL.Vec(BuildFailure)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeploymentFailures' : IDL.Func(
      [],
      [IDL.Vec(DeploymentFailure)],
      ['query'],
    ),
  'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
  'getInstagramStories' : IDL.Func([], [IDL.Vec(InstagramFeedItem)], ['query']),
  'getLatestBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getPopularShopProducts' : IDL.Func([], [IDL.Vec(ShopProduct)], ['query']),
  'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getPublishedBlogsPaginated' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'getPublishedInstagramFeedItems' : IDL.Func(
      [],
      [IDL.Vec(InstagramFeedItem)],
      ['query'],
    ),
  'getPublishedShopProducts' : IDL.Func([], [IDL.Vec(ShopProduct)], ['query']),
  'getShopProductsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ShopProduct)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementBlogViewCount' : IDL.Func([IDL.Text], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
  'registerBuildFailure' : IDL.Func([], [], []),
  'registerDeploymentFailure' : IDL.Func([], [], []),
  'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([ContactSubmission], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'triggerPublicationCheck' : IDL.Func([], [], []),
  'updateAdminSettings' : IDL.Func([AdminSettings], [], []),
  'updateBlogCategory' : IDL.Func([BlogCategory], [], []),
  'updateBlogPost' : IDL.Func([BlogPost], [], []),
  'updateInstagramFeedItem' : IDL.Func([InstagramFeedItem], [], []),
  'updateShopCategory' : IDL.Func([ShopCategory], [], []),
  'updateShopProduct' : IDL.Func([ShopProduct], [], []),
  'updateTravelStyle' : IDL.Func([TravelStyleUpdate], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const BlogCategory = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const InstagramFeedItem = IDL.Record({
    'id' : IDL.Text,
    'link' : IDL.Opt(IDL.Text),
    'published' : IDL.Bool,
    'mediaUrl' : IDL.Text,
    'story' : IDL.Bool,
    'timestamp' : Time,
    'caption' : IDL.Text,
    'mediaType' : IDL.Text,
  });
  const ShopCategory = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
  });
  const ShopProduct = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'inventory' : IDL.Nat,
    'published' : IDL.Bool,
    'popular' : IDL.Bool,
    'description' : IDL.Text,
    'timestamp' : Time,
    'category' : IDL.Text,
    'affiliateLink' : IDL.Text,
    'price' : IDL.Float64,
    'images' : IDL.Vec(IDL.Text),
  });
  const TravelStyle = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'timestamp' : Time,
    'baseImage' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EmailCapture = IDL.Record({ 'email' : IDL.Text, 'timestamp' : Time });
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'categories' : IDL.Vec(IDL.Text),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'published' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Opt(Time),
    'directPublish' : IDL.Bool,
    'author' : IDL.Text,
    'coverImage' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'excerpt' : IDL.Text,
    'scheduledAt' : IDL.Opt(Time),
    'images' : IDL.Vec(IDL.Text),
  });
  const AdminSettings = IDL.Record({
    'instagramApiKey' : IDL.Text,
    'comingSoonEnabled' : IDL.Bool,
    'tiktokApiKey' : IDL.Text,
  });
  const ContactSubmission = IDL.Record({
    'id' : IDL.Text,
    'consent' : IDL.Bool,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'language' : IDL.Text,
    'newsletter' : IDL.Bool,
  });
  const BuildFailure = IDL.Record({
    'failed_attempts' : IDL.Nat,
    'failed_step' : IDL.Text,
    'error_message' : IDL.Text,
    'timestamp' : Time,
    'environment' : IDL.Text,
  });
  const DeploymentFailure = IDL.Record({
    'failed_attempts' : IDL.Nat,
    'failed_step' : IDL.Text,
    'error_message' : IDL.Text,
    'timestamp' : Time,
    'environment' : IDL.Text,
  });
  const FileReference = IDL.Record({ 'hash' : IDL.Text, 'path' : IDL.Text });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TravelStyleUpdate = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'baseImage' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addBlogCategory' : IDL.Func([BlogCategory], [], []),
    'addInstagramFeedItem' : IDL.Func([InstagramFeedItem], [], []),
    'addShopCategory' : IDL.Func([ShopCategory], [], []),
    'addShopProduct' : IDL.Func([ShopProduct], [], []),
    'addTravelStyle' : IDL.Func([TravelStyle], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'captureEmail' : IDL.Func([EmailCapture], [], []),
    'createBlogPost' : IDL.Func([BlogPost], [], []),
    'deleteBlogCategory' : IDL.Func([IDL.Text], [], []),
    'deleteBlogPost' : IDL.Func([IDL.Text], [], []),
    'deleteInstagramFeedItem' : IDL.Func([IDL.Text], [], []),
    'deleteShopCategory' : IDL.Func([IDL.Text], [], []),
    'deleteShopProduct' : IDL.Func([IDL.Text], [], []),
    'deleteTravelStyle' : IDL.Func([IDL.Text], [], []),
    'dropFileReference' : IDL.Func([IDL.Text], [], []),
    'fetchInstagramFeed' : IDL.Func([], [IDL.Text], []),
    'fetchInstagramLogo' : IDL.Func([], [IDL.Text], []),
    'fetchTikTokFeed' : IDL.Func([], [IDL.Text], []),
    'getAdminSettings' : IDL.Func([], [IDL.Opt(AdminSettings)], ['query']),
    'getAllBlogCategories' : IDL.Func([], [IDL.Vec(BlogCategory)], ['query']),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllBlogViewCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getAllCapturedEmails' : IDL.Func([], [IDL.Vec(EmailCapture)], ['query']),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getAllInstagramFeedItems' : IDL.Func(
        [],
        [IDL.Vec(InstagramFeedItem)],
        ['query'],
      ),
    'getAllShopCategories' : IDL.Func([], [IDL.Vec(ShopCategory)], ['query']),
    'getAllShopProducts' : IDL.Func([], [IDL.Vec(ShopProduct)], ['query']),
    'getAllTravelStyles' : IDL.Func([], [IDL.Vec(TravelStyle)], ['query']),
    'getAllUsersWithProfiles' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Opt(UserProfile)))],
        ['query'],
      ),
    'getBlogPost' : IDL.Func([IDL.Text], [IDL.Opt(BlogPost)], ['query']),
    'getBlogPostsByAuthor' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getBlogPostsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getBlogPostsByTag' : IDL.Func([IDL.Text], [IDL.Vec(BlogPost)], ['query']),
    'getBlogViewCount' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getBuildFailures' : IDL.Func([], [IDL.Vec(BuildFailure)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeploymentFailures' : IDL.Func(
        [],
        [IDL.Vec(DeploymentFailure)],
        ['query'],
      ),
    'getFileReference' : IDL.Func([IDL.Text], [FileReference], ['query']),
    'getInstagramStories' : IDL.Func(
        [],
        [IDL.Vec(InstagramFeedItem)],
        ['query'],
      ),
    'getLatestBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getPopularShopProducts' : IDL.Func([], [IDL.Vec(ShopProduct)], ['query']),
    'getPublishedBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getPublishedBlogsPaginated' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'getPublishedInstagramFeedItems' : IDL.Func(
        [],
        [IDL.Vec(InstagramFeedItem)],
        ['query'],
      ),
    'getPublishedShopProducts' : IDL.Func(
        [],
        [IDL.Vec(ShopProduct)],
        ['query'],
      ),
    'getShopProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ShopProduct)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementBlogViewCount' : IDL.Func([IDL.Text], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listFileReferences' : IDL.Func([], [IDL.Vec(FileReference)], ['query']),
    'registerBuildFailure' : IDL.Func([], [], []),
    'registerDeploymentFailure' : IDL.Func([], [], []),
    'registerFileReference' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([ContactSubmission], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'triggerPublicationCheck' : IDL.Func([], [], []),
    'updateAdminSettings' : IDL.Func([AdminSettings], [], []),
    'updateBlogCategory' : IDL.Func([BlogCategory], [], []),
    'updateBlogPost' : IDL.Func([BlogPost], [], []),
    'updateInstagramFeedItem' : IDL.Func([InstagramFeedItem], [], []),
    'updateShopCategory' : IDL.Func([ShopCategory], [], []),
    'updateShopProduct' : IDL.Func([ShopProduct], [], []),
    'updateTravelStyle' : IDL.Func([TravelStyleUpdate], [], []),
  });
};

export const init = ({ IDL }) => { return []; };