/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    id: string;
    categories: Array<string>;
    title: string;
    content: string;
    published: boolean;
    tags: Array<string>;
    publishedAt?: Time;
    directPublish: boolean;
    author: string;
    coverImage?: string;
    timestamp: Time;
    excerpt: string;
    scheduledAt?: Time;
    images: Array<string>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface InstagramFeedItem {
    id: string;
    link?: string;
    published: boolean;
    mediaUrl: string;
    story: boolean;
    timestamp: Time;
    caption: string;
    mediaType: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface ContactSubmission {
    id: string;
    consent: boolean;
    subject: string;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface AdminSettings {
    instagramApiKey: string;
    comingSoonEnabled: boolean;
    tiktokApiKey: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface EmailCapture {
    email: string;
    timestamp: Time;
}
export interface ShopProduct {
    id: string;
    title: string;
    featured: boolean;
    inventory: bigint;
    published: boolean;
    popular: boolean;
    description: string;
    timestamp: Time;
    category: string;
    affiliateLink: string;
    price: number;
    images: Array<string>;
}
export interface DeploymentFailure {
    failed_attempts: bigint;
    failed_step: string;
    error_message: string;
    timestamp: Time;
    environment: string;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface BuildFailure {
    failed_attempts: bigint;
    failed_step: string;
    error_message: string;
    timestamp: Time;
    environment: string;
}
export interface ShopCategory {
    id: string;
    name: string;
    description: string;
    timestamp: Time;
}
export interface FileReference {
    hash: string;
    path: string;
}
export interface BlogCategory {
    id: string;
    name: string;
    description: string;
    timestamp: Time;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
    language: string;
    newsletter: boolean;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobsToDelete(): Promise<Array<string>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<string>): Promise<void>;
    _caffeineStorageCreateCertificate(blob_hash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addBlogCategory(category: BlogCategory): Promise<void>;
    addInstagramFeedItem(item: InstagramFeedItem): Promise<void>;
    addShopCategory(category: ShopCategory): Promise<void>;
    addShopProduct(product: ShopProduct): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    captureEmail(capture: EmailCapture): Promise<void>;
    createBlogPost(post: BlogPost): Promise<void>;
    deleteBlogCategory(id: string): Promise<void>;
    deleteBlogPost(id: string): Promise<void>;
    deleteInstagramFeedItem(id: string): Promise<void>;
    deleteShopCategory(id: string): Promise<void>;
    deleteShopProduct(id: string): Promise<void>;
    dropFileReference(path: string): Promise<void>;
    fetchInstagramFeed(): Promise<string>;
    fetchInstagramLogo(): Promise<string>;
    fetchTikTokFeed(): Promise<string>;
    getAdminSettings(): Promise<AdminSettings | null>;
    getAllBlogCategories(): Promise<Array<BlogCategory>>;
    getAllBlogPosts(): Promise<Array<BlogPost>>;
    getAllBlogViewCounts(): Promise<Array<[string, bigint]>>;
    getAllCapturedEmails(): Promise<Array<EmailCapture>>;
    getAllContactSubmissions(): Promise<Array<ContactSubmission>>;
    getAllInstagramFeedItems(): Promise<Array<InstagramFeedItem>>;
    getAllShopCategories(): Promise<Array<ShopCategory>>;
    getAllShopProducts(): Promise<Array<ShopProduct>>;
    getAllUsersWithProfiles(): Promise<Array<[Principal, UserProfile | null]>>;
    getBlogPost(id: string): Promise<BlogPost | null>;
    getBlogPostsByAuthor(author: string): Promise<Array<BlogPost>>;
    getBlogPostsByCategory(category: string): Promise<Array<BlogPost>>;
    getBlogPostsByTag(tag: string): Promise<Array<BlogPost>>;
    getBlogViewCount(id: string): Promise<bigint>;
    getBuildFailures(): Promise<Array<BuildFailure>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDeploymentFailures(): Promise<Array<DeploymentFailure>>;
    getFileReference(path: string): Promise<FileReference>;
    getInstagramStories(): Promise<Array<InstagramFeedItem>>;
    getLatestBlogPosts(): Promise<Array<BlogPost>>;
    getPopularShopProducts(): Promise<Array<ShopProduct>>;
    getPublishedBlogPosts(): Promise<Array<BlogPost>>;
    getPublishedBlogsPaginated(offset: bigint, limit: bigint): Promise<Array<BlogPost>>;
    getPublishedInstagramFeedItems(): Promise<Array<InstagramFeedItem>>;
    getPublishedShopProducts(): Promise<Array<ShopProduct>>;
    getShopProductsByCategory(category: string): Promise<Array<ShopProduct>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    incrementBlogViewCount(id: string): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    listFileReferences(): Promise<Array<FileReference>>;
    registerBuildFailure(): Promise<void>;
    registerDeploymentFailure(): Promise<void>;
    registerFileReference(path: string, hash: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitContactForm(submission: ContactSubmission): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    triggerPublicationCheck(): Promise<void>;
    updateAdminSettings(settings: AdminSettings): Promise<void>;
    updateBlogCategory(category: BlogCategory): Promise<void>;
    updateBlogPost(post: BlogPost): Promise<void>;
    updateInstagramFeedItem(item: InstagramFeedItem): Promise<void>;
    updateShopCategory(category: ShopCategory): Promise<void>;
    updateShopProduct(product: ShopProduct): Promise<void>;
}
import type { AdminSettings as _AdminSettings, BlogPost as _BlogPost, InstagramFeedItem as _InstagramFeedItem, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobsToDelete(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addBlogCategory(arg0: BlogCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addBlogCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBlogCategory(arg0);
            return result;
        }
    }
    async addInstagramFeedItem(arg0: InstagramFeedItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addInstagramFeedItem(to_candid_InstagramFeedItem_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addInstagramFeedItem(to_candid_InstagramFeedItem_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addShopCategory(arg0: ShopCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addShopCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShopCategory(arg0);
            return result;
        }
    }
    async addShopProduct(arg0: ShopProduct): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addShopProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShopProduct(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async captureEmail(arg0: EmailCapture): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.captureEmail(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.captureEmail(arg0);
            return result;
        }
    }
    async createBlogPost(arg0: BlogPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createBlogPost(to_candid_BlogPost_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBlogPost(to_candid_BlogPost_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteBlogCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogCategory(arg0);
            return result;
        }
    }
    async deleteBlogPost(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBlogPost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBlogPost(arg0);
            return result;
        }
    }
    async deleteInstagramFeedItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteInstagramFeedItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteInstagramFeedItem(arg0);
            return result;
        }
    }
    async deleteShopCategory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShopCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShopCategory(arg0);
            return result;
        }
    }
    async deleteShopProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShopProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShopProduct(arg0);
            return result;
        }
    }
    async dropFileReference(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.dropFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.dropFileReference(arg0);
            return result;
        }
    }
    async fetchInstagramFeed(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchInstagramFeed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchInstagramFeed();
            return result;
        }
    }
    async fetchInstagramLogo(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchInstagramLogo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchInstagramLogo();
            return result;
        }
    }
    async fetchTikTokFeed(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.fetchTikTokFeed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.fetchTikTokFeed();
            return result;
        }
    }
    async getAdminSettings(): Promise<AdminSettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminSettings();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminSettings();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBlogCategories(): Promise<Array<BlogCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogCategories();
            return result;
        }
    }
    async getAllBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogPosts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogPosts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBlogViewCounts(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBlogViewCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBlogViewCounts();
            return result;
        }
    }
    async getAllCapturedEmails(): Promise<Array<EmailCapture>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCapturedEmails();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCapturedEmails();
            return result;
        }
    }
    async getAllContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactSubmissions();
            return result;
        }
    }
    async getAllInstagramFeedItems(): Promise<Array<InstagramFeedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInstagramFeedItems();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInstagramFeedItems();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllShopCategories(): Promise<Array<ShopCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShopCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShopCategories();
            return result;
        }
    }
    async getAllShopProducts(): Promise<Array<ShopProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShopProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShopProducts();
            return result;
        }
    }
    async getAllUsersWithProfiles(): Promise<Array<[Principal, UserProfile | null]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsersWithProfiles();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsersWithProfiles();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPost(arg0: string): Promise<BlogPost | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPost(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPost(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostsByAuthor(arg0: string): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostsByAuthor(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostsByAuthor(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostsByCategory(arg0: string): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostsByCategory(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostsByCategory(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogPostsByTag(arg0: string): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPostsByTag(arg0);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPostsByTag(arg0);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBlogViewCount(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogViewCount(arg0);
            return result;
        }
    }
    async getBuildFailures(): Promise<Array<BuildFailure>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBuildFailures();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBuildFailures();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeploymentFailures(): Promise<Array<DeploymentFailure>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeploymentFailures();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeploymentFailures();
            return result;
        }
    }
    async getFileReference(arg0: string): Promise<FileReference> {
        if (this.processError) {
            try {
                const result = await this.actor.getFileReference(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFileReference(arg0);
            return result;
        }
    }
    async getInstagramStories(): Promise<Array<InstagramFeedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInstagramStories();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInstagramStories();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLatestBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestBlogPosts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestBlogPosts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPopularShopProducts(): Promise<Array<ShopProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPopularShopProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPopularShopProducts();
            return result;
        }
    }
    async getPublishedBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedBlogPosts();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedBlogPosts();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedBlogsPaginated(arg0: bigint, arg1: bigint): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedBlogsPaginated(arg0, arg1);
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedBlogsPaginated(arg0, arg1);
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedInstagramFeedItems(): Promise<Array<InstagramFeedItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedInstagramFeedItems();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedInstagramFeedItems();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedShopProducts(): Promise<Array<ShopProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedShopProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedShopProducts();
            return result;
        }
    }
    async getShopProductsByCategory(arg0: string): Promise<Array<ShopProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShopProductsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShopProductsByCategory(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async incrementBlogViewCount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.incrementBlogViewCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.incrementBlogViewCount(arg0);
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listFileReferences(): Promise<Array<FileReference>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFileReferences();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFileReferences();
            return result;
        }
    }
    async registerBuildFailure(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerBuildFailure();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerBuildFailure();
            return result;
        }
    }
    async registerDeploymentFailure(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerDeploymentFailure();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerDeploymentFailure();
            return result;
        }
    }
    async registerFileReference(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerFileReference(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerFileReference(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitContactForm(arg0: ContactSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async triggerPublicationCheck(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.triggerPublicationCheck();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.triggerPublicationCheck();
            return result;
        }
    }
    async updateAdminSettings(arg0: AdminSettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAdminSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAdminSettings(arg0);
            return result;
        }
    }
    async updateBlogCategory(arg0: BlogCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogCategory(arg0);
            return result;
        }
    }
    async updateBlogPost(arg0: BlogPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBlogPost(to_candid_BlogPost_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBlogPost(to_candid_BlogPost_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateInstagramFeedItem(arg0: InstagramFeedItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInstagramFeedItem(to_candid_InstagramFeedItem_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInstagramFeedItem(to_candid_InstagramFeedItem_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateShopCategory(arg0: ShopCategory): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShopCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShopCategory(arg0);
            return result;
        }
    }
    async updateShopProduct(arg0: ShopProduct): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShopProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShopProduct(arg0);
            return result;
        }
    }
}
function from_candid_BlogPost_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlogPost): BlogPost {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_InstagramFeedItem_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InstagramFeedItem): InstagramFeedItem {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminSettings]): AdminSettings | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BlogPost]): BlogPost | null {
    return value.length === 0 ? null : from_candid_BlogPost_n16(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categories: Array<string>;
    title: string;
    content: string;
    published: boolean;
    tags: Array<string>;
    publishedAt: [] | [_Time];
    directPublish: boolean;
    author: string;
    coverImage: [] | [string];
    timestamp: _Time;
    excerpt: string;
    scheduledAt: [] | [_Time];
    images: Array<string>;
}): {
    id: string;
    categories: Array<string>;
    title: string;
    content: string;
    published: boolean;
    tags: Array<string>;
    publishedAt?: Time;
    directPublish: boolean;
    author: string;
    coverImage?: string;
    timestamp: Time;
    excerpt: string;
    scheduledAt?: Time;
    images: Array<string>;
} {
    return {
        id: value.id,
        categories: value.categories,
        title: value.title,
        content: value.content,
        published: value.published,
        tags: value.tags,
        publishedAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.publishedAt)),
        directPublish: value.directPublish,
        author: value.author,
        coverImage: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.coverImage)),
        timestamp: value.timestamp,
        excerpt: value.excerpt,
        scheduledAt: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.scheduledAt)),
        images: value.images
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    link: [] | [string];
    published: boolean;
    mediaUrl: string;
    story: boolean;
    timestamp: _Time;
    caption: string;
    mediaType: string;
}): {
    id: string;
    link?: string;
    published: boolean;
    mediaUrl: string;
    story: boolean;
    timestamp: Time;
    caption: string;
    mediaType: string;
} {
    return {
        id: value.id,
        link: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.link)),
        published: value.published,
        mediaUrl: value.mediaUrl,
        story: value.story,
        timestamp: value.timestamp,
        caption: value.caption,
        mediaType: value.mediaType
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_tuple_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, [] | [_UserProfile]]): [Principal, UserProfile | null] {
    return [
        value[0],
        from_candid_opt_n25(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BlogPost>): Array<BlogPost> {
    return value.map((x)=>from_candid_BlogPost_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InstagramFeedItem>): Array<InstagramFeedItem> {
    return value.map((x)=>from_candid_InstagramFeedItem_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, [] | [_UserProfile]]>): Array<[Principal, UserProfile | null]> {
    return value.map((x)=>from_candid_tuple_n24(_uploadFile, _downloadFile, x));
}
function to_candid_BlogPost_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BlogPost): _BlogPost {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_InstagramFeedItem_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InstagramFeedItem): _InstagramFeedItem {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categories: Array<string>;
    title: string;
    content: string;
    published: boolean;
    tags: Array<string>;
    publishedAt?: Time;
    directPublish: boolean;
    author: string;
    coverImage?: string;
    timestamp: Time;
    excerpt: string;
    scheduledAt?: Time;
    images: Array<string>;
}): {
    id: string;
    categories: Array<string>;
    title: string;
    content: string;
    published: boolean;
    tags: Array<string>;
    publishedAt: [] | [_Time];
    directPublish: boolean;
    author: string;
    coverImage: [] | [string];
    timestamp: _Time;
    excerpt: string;
    scheduledAt: [] | [_Time];
    images: Array<string>;
} {
    return {
        id: value.id,
        categories: value.categories,
        title: value.title,
        content: value.content,
        published: value.published,
        tags: value.tags,
        publishedAt: value.publishedAt ? candid_some(value.publishedAt) : candid_none(),
        directPublish: value.directPublish,
        author: value.author,
        coverImage: value.coverImage ? candid_some(value.coverImage) : candid_none(),
        timestamp: value.timestamp,
        excerpt: value.excerpt,
        scheduledAt: value.scheduledAt ? candid_some(value.scheduledAt) : candid_none(),
        images: value.images
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    link?: string;
    published: boolean;
    mediaUrl: string;
    story: boolean;
    timestamp: Time;
    caption: string;
    mediaType: string;
}): {
    id: string;
    link: [] | [string];
    published: boolean;
    mediaUrl: string;
    story: boolean;
    timestamp: _Time;
    caption: string;
    mediaType: string;
} {
    return {
        id: value.id,
        link: value.link ? candid_some(value.link) : candid_none(),
        published: value.published,
        mediaUrl: value.mediaUrl,
        story: value.story,
        timestamp: value.timestamp,
        caption: value.caption,
        mediaType: value.mediaType
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
